kind: pipeline
type: docker
name: default

steps:
  - name: generate
    pull: if-not-exists
    image: hkccr.ccs.tencentyun.com/xiaoqidun/build
    commands:
      - build -f build.sh -i gitcz.go -o release/gitcz
  - name: build
    pull: if-not-exists
    image: xiaoqidun/goenv
    commands:
      - ./ build.sh
  - name: upload
    image: xiaoqidun/gocos
    settings:
      secret_id:
        from_secret: cos_secret_id
      secret_key:
        from_secret: cos_secret_key
      bucket_url:
        from_secret: cos_bucket_url
      source: release/
      target: product/gitcz
      strip_prefix: release/